### ISSUE TITLE
changing description to be more accurate

### ISSUE THREAD

**Issue by mahmoodahmad100** [BootstrapDash/PurpleAdmin-Free-Angular-Admin-Template#1]
please change the description of the repo as in the following(to be more accurate):

from 

> Purple Admin Angular Admin is a free admin template based on Bootstrap 4 and AngularJS 

to

> Purple Admin Angular Admin is a free admin template based on Bootstrap 4 and Angular
**(I recommend this)**

or

> Purple Admin Angular Admin is a free admin template based on Bootstrap 4 and Angular 2+

or

> Purple Admin Angular Admin is a free admin template based on Bootstrap 4 and Angular 7

the change in **_AngularJS_** 

Thanks

**Comment by bootstrapdash-team** [comment]
@mahmoodahmad100 Thank you for pointing out this mistake. We have corrected it.
